// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7stb9Jwsm7F-nQ7omjfX-vaXo3Qi3_w',
    appId: '1:1033141014094:web:83550c271ef9d0cc55fd1f',
    messagingSenderId: '1033141014094',
    projectId: 'crud-8b3e4',
    authDomain: 'crud-8b3e4.firebaseapp.com',
    storageBucket: 'crud-8b3e4.firebasestorage.app',
    measurementId: 'G-64Y7HW9RNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAsuieY5RtRyrzRU-8GJrUmoLwlNh4BQ',
    appId: '1:1033141014094:android:5ce1fdf61b52411b55fd1f',
    messagingSenderId: '1033141014094',
    projectId: 'crud-8b3e4',
    storageBucket: 'crud-8b3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLeHDghKxMjMqk1TM-5h5AvFdSQ4zrLk',
    appId: '1:1033141014094:ios:d6565e3c6644929b55fd1f',
    messagingSenderId: '1033141014094',
    projectId: 'crud-8b3e4',
    storageBucket: 'crud-8b3e4.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmLeHDghKxMjMqk1TM-5h5AvFdSQ4zrLk',
    appId: '1:1033141014094:ios:d6565e3c6644929b55fd1f',
    messagingSenderId: '1033141014094',
    projectId: 'crud-8b3e4',
    storageBucket: 'crud-8b3e4.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn7stb9Jwsm7F-nQ7omjfX-vaXo3Qi3_w',
    appId: '1:1033141014094:web:18deb705c13c58d855fd1f',
    messagingSenderId: '1033141014094',
    projectId: 'crud-8b3e4',
    authDomain: 'crud-8b3e4.firebaseapp.com',
    storageBucket: 'crud-8b3e4.firebasestorage.app',
    measurementId: 'G-JYSH4B0TE2',
  );
}
